### ISSUE TITLE
Question about parameters

### ISSUE THREAD

**Issue by szriru** [TencentARC/InstantMesh#35]
I noticed that the texture quality of my output did not meet my expectations, especially when compared to the demo results which looked significantly better.

Could you please help me understand which parameters might influence the texture quality? Additionally, I would like to know the specific parameters used in the demo for comparison.

Here are the default parameters I used:

```yaml
model_config:
  target: src.models.lrm_mesh.InstantMesh
  params:
    encoder_feat_dim: 768
    encoder_freeze: false
    encoder_model_name: facebook/dino-vitb16
    transformer_dim: 1024
    transformer_layers: 16
    transformer_heads: 16
    triplane_low_res: 32
    triplane_high_res: 64
    triplane_dim: 80
    rendering_samples_per_ray: 64
    grid_res: 128
    grid_scale: 2.1


infer_config:
  unet_path: ckpts/diffusion_pytorch_model.bin
  model_path: ckpts/instant_mesh_large.ckpt
  texture_resolution: 1024
  render_resolution: 1024
```
Input image
![megmin-rembg](https://github.com/TencentARC/InstantMesh/assets/106813119/a0300ae4-4918-4dbe-93a6-a7a985ce3407)

Result
![スクリーンショット 2024-04-22 073417](https://github.com/TencentARC/InstantMesh/assets/106813119/e530d671-d294-48a5-8733-585a2755ecb3)

Any guidance or suggestions would be greatly appreciated!

Thank you for your time and assistance.
