### ISSUE TITLE
how to increase the quality of mesh

### ISSUE THREAD

**Issue by sumanttyagi** [TencentARC/InstantMesh#84]
In the config file i see texture resolution does it really helps in improving the quality of meshes generated ?
Please comment what all these parameters mean ?
1. texture_resolution and render_resolution in - https://github.com/TencentARC/InstantMesh/blob/main/configs/instant-mesh-large.yaml
```
infer_config:
  unet_path: ckpts/diffusion_pytorch_model.bin
  model_path: ckpts/instant_mesh_large.ckpt
  texture_resolution: 1024
  render_resolution: 512
```
2. mesh threshold - https://github.com/TencentARC/InstantMesh/blob/main/configs/instant-nerf-large.yaml
```
infer_config:
  unet_path: ckpts/diffusion_pytorch_model.bin
  model_path: ckpts/instant_nerf_large.ckpt
  mesh_threshold: 10.0
  mesh_resolution: 256
  render_resolution: 384
```
